version: '3.7'

networks:
  mongodb_net:
    driver: bridge
    ipam:
      driver: default
      config:
      # Change this subnet range if it conflicts with your host network
        - subnet: 192.168.213.0/24
          gateway: 192.168.213.1
services:
    mongodb:
      image: mongo:latest
      container_name: mongodb
      hostname: mongodb
      networks:
        - mongodb_net
      ports:
        - 27017:27017
      deploy:
              restart_policy:
                condition: unless-stopped
                delay: 5s
                max_attempts: 3
                window: 120s
    mongoclient:
      image: mongoclient/mongoclient:latest
      container_name: mongoclient
      hostname: mongoclient
      depends_on:
        - mongodb
      networks:
        - mongodb_net
      ports:
        - 3300:3000
      deploy:
              restart_policy:
                condition: unless-stopped
                delay: 5s
                max_attempts: 3
                window: 120s
